In [3]:
import pandas as pd 
import numpy as np 
import time
from tqdm import tqdm  # ✅ add tqdm
import ollama
import re
import json
import concurrent.futures
import psutil



import threading

In [2]:

# def extract_json(text):
#     # remove code fences if they exist
#     text = re.sub(r"^```[a-zA-Z]*\n?", "", text.strip())  # remove leading ```json or ```
#     text = re.sub(r"```$", "", text.strip())              # remove trailing ```
    
#     # extract first JSON object if multiple
#     match = re.search(r"\{.*\}", text, re.DOTALL)
#     if match:
#         return match.group(0)
#     return text

In [22]:
# dataframe_name = 'DividedDataset/resume_till_100_rows.csv'

In [23]:
# temp_df = pd.read_csv(dataframe_name)

In [1]:
dataframe_name = 'DividedDataset/resume_till_1560_rows.csv'
temp_df = pd.read_csv(dataframe_name)



def extract_json(text):
    # remove code fences if they exist
    text = re.sub(r"^```[a-zA-Z]*\n?", "", text.strip())  # remove leading ```json or ```
    text = re.sub(r"```$", "", text.strip())              # remove trailing ```
    
    # extract first JSON object if multiple
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match:
        return match.group(0)
    return text




atscoretemp = []   # make sure list is initialized
start_time = time.time()

for i in tqdm(range(len(temp_df)), desc="Processing resumes", unit="resume"):
    resume = temp_df.iloc[i,0]
    job    = temp_df.iloc[i,1]

    prompt_content = f"""
    You are an expert resume analyst. Your task is to analyze a candidate's resume and a job description to determine their fit. You MUST ONLY provide a JSON object in your response. Do not include any other text or conversational phrases.

    [JOB DESCRIPTION]
    {job}

    [CANDIDATE RESUME]
    {resume}

    Analyze the candidate's skills and experience against the job description.
    Provide a final match score on a scale from 1 to 100, where 1 is no match and 100 is a perfect match.
    
    Format your output strictly as a JSON object with the following keys:
    {{
      "match_score": int
    }}
    """

    response = ollama.chat(
        model='gemma3',
        messages=[{'role': 'user', 'content': prompt_content}]
    )

    try:
        raw_content = response['message']['content']
        json_str = extract_json(raw_content)   # 🧹 clean response
        ats_score_data = json.loads(json_str)
    
        match_score = ats_score_data.get('match_score', 'N/A')
        atscoretemp.append(match_score)

    except json.JSONDecodeError as e:
        print(f"\nError parsing JSON response at index {i}: {e}")
        print("Raw response:", response['message']['content'])


temp_df['new_ats'] = atscoretemp
temp_df.to_csv(dataframe_name, index=False, encoding='utf-8')

end_time = time.time()
elapsed_time = end_time - start_time
print(f"\n✅ Finished in {elapsed_time:.2f} seconds")

NameError: name 'time' is not defined

In [4]:


# --- Your Existing Code and Imports ---
dataframe_name = "DividedDataset/resume_till_1560_rows.csv"
temp_df = pd.read_csv(dataframe_name)

def extract_json(text):
    # remove code fences if they exist
    text = re.sub(r"^```[a-zA-Z]*\n?", "", text.strip())
    text = re.sub(r"```$", "", text.strip())
    
    # extract first JSON object if multiple
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match:
        return match.group(0)
    return text

# --- The Missing Function ---
def process_single_resume(resume_data):
    i, resume, jd = resume_data
    prompt_content = f"""
    You are an expert resume analyst. Your task is to analyze a candidate's resume and a job description to determine their fit. You MUST ONLY provide a JSON object in your response. Do not include any other text or conversational phrases.

    [JOB DESCRIPTION]
    {jd}

    [CANDIDATE RESUME]
    {resume}

    Analyze the candidate's skills and experience against the job description.
    Provide a final match score on a scale from 1 to 100, where 1 is no match and 100 is a perfect match.
    
    Format your output strictly as a JSON object with the following keys:
    {{
      "match_score": int
    }}
    """
    try:
        response = ollama.chat(
            model='gemma3',
            messages=[{'role': 'user', 'content': prompt_content}]
        )
        raw_content = response['message']['content']
        json_str = extract_json(raw_content)
        ats_score_data = json.loads(json_str)
        match_score = ats_score_data.get('match_score', 'N/A')
        return match_score
    except (json.JSONDecodeError, KeyError) as e:
        # print(f"\nError processing resume at index {i}: {e}") # Optional: Re-add for debugging
        return 'N/A'

# A global event to signal the monitor to stop
stop_event = threading.Event()

def monitor_cpu_daemon(max_cpu_percent=80, check_interval=5):
    """Monitors CPU usage and signals to stop if it exceeds the threshold."""
    print(f"Starting CPU monitor. Will terminate if CPU usage exceeds {max_cpu_percent}%.")
    while not stop_event.is_set():
        cpu_percent = psutil.cpu_percent(interval=1)
        print(f"Current CPU usage: {cpu_percent}%")
        if cpu_percent > max_cpu_percent:
            print(f"CPU usage ({cpu_percent}%) exceeded the limit of {max_cpu_percent}%. Stopping main process.")
            stop_event.set()
        time.sleep(check_interval)
    print("CPU monitor terminated.")

def run_parallel_pipeline_with_monitoring_revised(dataframe, max_workers=8, max_cpu_percent=80):
    start_time = time.time()
    data_to_process = [(i, row['resume'], row['jd']) for i, row in dataframe.iterrows()]
    
    # Start the CPU monitor daemon thread
    monitor_thread = threading.Thread(target=monitor_cpu_daemon, args=(max_cpu_percent,), daemon=True)
    monitor_thread.start()
    
    ats_scores = []
    
    try:
        with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
            # Map the processing function to the data
            results = executor.map(process_single_resume, data_to_process)
            
            # Use tqdm to show progress as results are completed
            ats_scores = list(tqdm(results, total=len(data_to_process), desc="Processing Resumes"))
            
    except Exception as e:
        print(f"Main process interrupted due to: {e}")
    finally:
        # Signal the monitor to stop and wait for it
        stop_event.set()
        monitor_thread.join()

    dataframe['new_ats'] = ats_scores
    dataframe.to_csv(dataframe_name, index=False, encoding='utf-8')

    end_time = time.time()
    elapsed_time = end_time - start_time
    print(f"\n✅ Finished in {elapsed_time:.2f} seconds")

# --- Call the function with your dataframe ---
run_parallel_pipeline_with_monitoring_revised(temp_df)

Starting CPU monitor. Will terminate if CPU usage exceeds 80%.

Processing Resumes:   0%|                                                                       | 0/60 [00:00<?, ?it/s]

Current CPU usage: 39.8%
Current CPU usage: 51.2%
Current CPU usage: 50.3%
Current CPU usage: 50.8%
Current CPU usage: 50.4%
Current CPU usage: 53.2%

Processing Resumes:   2%|█                                                              | 1/60 [00:36<36:02, 36.65s/it]

Current CPU usage: 52.1%
Current CPU usage: 50.4%
Current CPU usage: 52.2%
Current CPU usage: 50.2%
Current CPU usage: 56.5%
Current CPU usage: 51.8%
Current CPU usage: 51.6%
Current CPU usage: 51.0%
Current CPU usage: 51.2%
Current CPU usage: 51.5%
Current CPU usage: 52.0%
Current CPU usage: 50.6%
Current CPU usage: 56.2%
Current CPU usage: 50.9%
Current CPU usage: 52.1%
Current CPU usage: 51.9%
Current CPU usage: 51.3%
Current CPU usage: 50.3%
Current CPU usage: 50.2%

Processing Resumes:   3%|██                                                           | 2/60 [02:28<1:18:20, 81.04s/it]

Current CPU usage: 51.6%
Current CPU usage: 51.4%
Current CPU usage: 50.3%
Current CPU usage: 51.4%
Current CPU usage: 51.3%
Current CPU usage: 51.6%
Current CPU usage: 50.7%
Current CPU usage: 50.1%
Current CPU usage: 50.8%
Current CPU usage: 50.1%

Processing Resumes:   5%|███                                                          | 3/60 [03:28<1:07:49, 71.40s/it]

Current CPU usage: 61.7%
Current CPU usage: 51.2%
Current CPU usage: 50.4%
Current CPU usage: 50.3%
Current CPU usage: 51.4%
Current CPU usage: 51.9%

Processing Resumes:   7%|████▏                                                          | 4/60 [04:03<53:13, 57.04s/it]

Current CPU usage: 51.0%
Current CPU usage: 50.5%
Current CPU usage: 50.2%
Current CPU usage: 51.0%
Current CPU usage: 53.1%
Current CPU usage: 51.0%
Current CPU usage: 56.4%

Processing Resumes:  12%|███████▎                                                       | 7/60 [04:47<26:54, 30.46s/it]

Current CPU usage: 59.7%
Current CPU usage: 52.1%
Current CPU usage: 63.1%
Current CPU usage: 51.6%
Current CPU usage: 50.9%

Processing Resumes:  13%|████████▍                                                      | 8/60 [05:19<26:33, 30.65s/it]

Current CPU usage: 46.9%
Current CPU usage: 50.5%
Current CPU usage: 61.4%
Current CPU usage: 50.6%
Current CPU usage: 50.5%
Current CPU usage: 50.5%
Current CPU usage: 50.8%
Current CPU usage: 52.5%

Processing Resumes:  15%|█████████▍                                                     | 9/60 [06:02<28:46, 33.86s/it]

Current CPU usage: 50.1%
Current CPU usage: 50.3%
Current CPU usage: 50.1%
Current CPU usage: 50.6%
Current CPU usage: 53.2%
Current CPU usage: 50.8%

Processing Resumes:  17%|██████████▎                                                   | 10/60 [06:38<28:38, 34.38s/it]

Current CPU usage: 49.9%
Current CPU usage: 52.2%
Current CPU usage: 49.7%
Current CPU usage: 52.3%
Current CPU usage: 50.5%
Current CPU usage: 49.9%

Processing Resumes:  18%|███████████▎                                                  | 11/60 [07:15<28:41, 35.14s/it]

Current CPU usage: 50.4%
Current CPU usage: 50.5%
Current CPU usage: 51.0%
Current CPU usage: 50.4%
Current CPU usage: 50.1%
Current CPU usage: 50.3%
Current CPU usage: 50.3%
Current CPU usage: 53.1%

Processing Resumes:  20%|████████████▍                                                 | 12/60 [08:04<31:12, 39.02s/it]

Current CPU usage: 50.5%
Current CPU usage: 50.3%
Current CPU usage: 50.8%
Current CPU usage: 50.3%
Current CPU usage: 53.8%
Current CPU usage: 50.8%
Current CPU usage: 61.7%

Processing Resumes:  22%|█████████████▍                                                | 13/60 [08:46<31:07, 39.74s/it]

Current CPU usage: 56.9%
Current CPU usage: 50.5%
Current CPU usage: 53.3%
Current CPU usage: 49.9%
Current CPU usage: 49.9%
Current CPU usage: 50.1%
Current CPU usage: 50.9%

Processing Resumes:  23%|██████████████▍                                               | 14/60 [09:29<31:17, 40.80s/it]

Current CPU usage: 55.3%
Current CPU usage: 51.4%
Current CPU usage: 50.5%
Current CPU usage: 50.3%
Current CPU usage: 50.9%
Current CPU usage: 56.1%
Current CPU usage: 50.5%
Current CPU usage: 50.2%
Current CPU usage: 50.0%
Current CPU usage: 51.5%

Processing Resumes:  25%|███████████████▌                                              | 15/60 [10:30<35:00, 46.68s/it]

Current CPU usage: 55.8%
Current CPU usage: 49.9%
Current CPU usage: 50.3%
Current CPU usage: 52.4%
Current CPU usage: 53.1%
Current CPU usage: 53.1%

Processing Resumes:  27%|████████████████▌                                             | 16/60 [11:06<31:55, 43.54s/it]

Current CPU usage: 52.7%
Current CPU usage: 50.3%
Current CPU usage: 50.0%
Current CPU usage: 50.2%
Current CPU usage: 52.1%
Current CPU usage: 58.2%
Current CPU usage: 49.8%

Processing Resumes:  28%|█████████████████▌                                            | 17/60 [11:49<30:57, 43.20s/it]

Current CPU usage: 45.8%
Current CPU usage: 56.1%
Current CPU usage: 55.9%
Current CPU usage: 50.9%
Current CPU usage: 51.3%
Current CPU usage: 51.5%
Current CPU usage: 49.2%

Processing Resumes:  30%|██████████████████▌                                           | 18/60 [12:26<29:01, 41.47s/it]

Current CPU usage: 52.7%
Current CPU usage: 51.6%
Current CPU usage: 50.1%
Current CPU usage: 54.6%
Current CPU usage: 57.8%
Current CPU usage: 56.4%
Current CPU usage: 59.3%

Processing Resumes:  32%|███████████████████▋                                          | 19/60 [13:10<28:56, 42.35s/it]

Current CPU usage: 50.6%
Current CPU usage: 50.8%
Current CPU usage: 50.8%
Current CPU usage: 53.2%
Current CPU usage: 50.7%

Processing Resumes:  33%|████████████████████▋                                         | 20/60 [13:41<25:53, 38.85s/it]

Current CPU usage: 50.6%
Current CPU usage: 50.9%
Current CPU usage: 52.4%
Current CPU usage: 52.5%
Current CPU usage: 51.3%
Current CPU usage: 50.6%
Current CPU usage: 50.5%

Processing Resumes:  35%|█████████████████████▋                                        | 21/60 [14:24<26:04, 40.12s/it]

Current CPU usage: 53.4%
Current CPU usage: 51.8%
Current CPU usage: 50.7%
Current CPU usage: 50.6%
Current CPU usage: 52.5%
Current CPU usage: 49.9%
Current CPU usage: 50.9%

Processing Resumes:  37%|██████████████████████▋                                       | 22/60 [15:02<24:56, 39.38s/it]

Current CPU usage: 51.2%
Current CPU usage: 50.2%
Current CPU usage: 50.3%
Current CPU usage: 60.8%
Current CPU usage: 53.0%
Current CPU usage: 50.4%

Processing Resumes:  38%|███████████████████████▊                                      | 23/60 [15:40<24:02, 38.98s/it]

Current CPU usage: 50.1%
Current CPU usage: 50.1%
Current CPU usage: 50.8%
Current CPU usage: 52.9%
Current CPU usage: 50.3%
Current CPU usage: 49.8%
Current CPU usage: 50.5%
Current CPU usage: 53.6%

Processing Resumes:  40%|████████████████████████▊                                     | 24/60 [16:29<25:17, 42.16s/it]

Current CPU usage: 52.1%
Current CPU usage: 50.6%
Current CPU usage: 50.9%
Current CPU usage: 52.4%
Current CPU usage: 50.6%
Current CPU usage: 53.6%
Current CPU usage: 50.9%
Current CPU usage: 51.2%

Processing Resumes:  42%|█████████████████████████▊                                    | 25/60 [17:16<25:24, 43.56s/it]

Current CPU usage: 50.8%
Current CPU usage: 51.0%
Current CPU usage: 52.9%
Current CPU usage: 50.6%
Current CPU usage: 50.4%
Current CPU usage: 50.8%
Current CPU usage: 50.8%
Current CPU usage: 52.7%

Processing Resumes:  43%|██████████████████████████▊                                   | 26/60 [18:03<25:17, 44.64s/it]

Current CPU usage: 51.0%
Current CPU usage: 50.9%
Current CPU usage: 51.0%
Current CPU usage: 50.1%
Current CPU usage: 51.9%
Current CPU usage: 50.5%
Current CPU usage: 50.1%
Current CPU usage: 51.7%
Current CPU usage: 50.2%
Current CPU usage: 52.3%
Current CPU usage: 50.0%

Processing Resumes:  45%|███████████████████████████▉                                  | 27/60 [19:11<28:16, 51.40s/it]

Current CPU usage: 50.2%
Current CPU usage: 50.1%
Current CPU usage: 50.1%
Current CPU usage: 52.9%
Current CPU usage: 50.1%
Current CPU usage: 49.7%
Current CPU usage: 50.3%

Processing Resumes:  47%|████████████████████████████▉                                 | 28/60 [19:51<25:39, 48.12s/it]

Current CPU usage: 59.1%
Current CPU usage: 53.3%
Current CPU usage: 50.1%
Current CPU usage: 50.0%
Current CPU usage: 49.9%
Current CPU usage: 50.1%
Current CPU usage: 52.4%
Current CPU usage: 51.0%

Processing Resumes:  48%|█████████████████████████████▉                                | 29/60 [20:39<24:46, 47.96s/it]

Current CPU usage: 51.2%
Current CPU usage: 50.6%
Current CPU usage: 49.8%
Current CPU usage: 52.9%
Current CPU usage: 51.3%
Current CPU usage: 50.7%
Current CPU usage: 50.0%

Processing Resumes:  50%|███████████████████████████████                               | 30/60 [21:20<22:59, 46.00s/it]

Current CPU usage: 50.3%
Current CPU usage: 54.6%
Current CPU usage: 51.0%
Current CPU usage: 50.4%
Current CPU usage: 51.1%
Current CPU usage: 50.8%
Current CPU usage: 54.2%
Current CPU usage: 50.7%

Processing Resumes:  52%|████████████████████████████████                              | 31/60 [22:09<22:36, 46.79s/it]

Current CPU usage: 50.4%
Current CPU usage: 50.4%
Current CPU usage: 50.5%
Current CPU usage: 52.0%
Current CPU usage: 50.7%
Current CPU usage: 46.5%

Processing Resumes:  53%|█████████████████████████████████                             | 32/60 [22:44<20:12, 43.31s/it]

Current CPU usage: 49.9%
Current CPU usage: 49.9%
Current CPU usage: 52.9%
Current CPU usage: 50.7%
Current CPU usage: 50.4%
Current CPU usage: 50.8%
Current CPU usage: 50.1%
Current CPU usage: 52.7%

Processing Resumes:  55%|██████████████████████████████████                            | 33/60 [23:34<20:23, 45.30s/it]

Current CPU usage: 49.9%
Current CPU usage: 50.3%
Current CPU usage: 50.1%
Current CPU usage: 50.4%
Current CPU usage: 52.2%
Current CPU usage: 49.7%
Current CPU usage: 50.5%

Processing Resumes:  57%|███████████████████████████████████▏                          | 34/60 [24:16<19:09, 44.21s/it]

Current CPU usage: 50.3%
Current CPU usage: 50.2%
Current CPU usage: 52.6%
Current CPU usage: 50.7%
Current CPU usage: 50.5%
Current CPU usage: 50.3%
Current CPU usage: 50.5%

Processing Resumes:  58%|████████████████████████████████████▏                         | 35/60 [24:59<18:16, 43.86s/it]

Current CPU usage: 53.3%
Current CPU usage: 50.4%
Current CPU usage: 50.6%
Current CPU usage: 50.3%
Current CPU usage: 51.3%
Current CPU usage: 52.8%
Current CPU usage: 50.5%
Current CPU usage: 51.5%
Current CPU usage: 50.8%

Processing Resumes:  60%|█████████████████████████████████████▏                        | 36/60 [25:53<18:49, 47.08s/it]

Current CPU usage: 50.6%
Current CPU usage: 52.4%
Current CPU usage: 51.4%
Current CPU usage: 50.5%
Current CPU usage: 50.1%

Processing Resumes:  62%|██████████████████████████████████████▏                       | 37/60 [26:21<15:49, 41.29s/it]

Current CPU usage: 50.7%
Current CPU usage: 52.7%
Current CPU usage: 49.8%
Current CPU usage: 50.3%

Processing Resumes:  63%|███████████████████████████████████████▎                      | 38/60 [26:47<13:27, 36.72s/it]

Current CPU usage: 50.1%
Current CPU usage: 50.5%
Current CPU usage: 51.6%
Current CPU usage: 50.5%
Current CPU usage: 50.0%
Current CPU usage: 50.3%
Current CPU usage: 50.1%
Current CPU usage: 53.2%

Processing Resumes:  65%|████████████████████████████████████████▎                     | 39/60 [27:34<13:55, 39.78s/it]

Current CPU usage: 50.8%
Current CPU usage: 49.9%
Current CPU usage: 50.0%
Current CPU usage: 50.1%

Processing Resumes:  67%|█████████████████████████████████████████▎                    | 40/60 [27:57<11:33, 34.67s/it]

Current CPU usage: 53.3%
Current CPU usage: 50.2%
Current CPU usage: 49.9%
Current CPU usage: 50.5%

Processing Resumes:  68%|██████████████████████████████████████████▎                   | 41/60 [28:23<10:12, 32.26s/it]

Current CPU usage: 50.7%
Current CPU usage: 53.8%
Current CPU usage: 50.6%
Current CPU usage: 49.7%

Processing Resumes:  70%|███████████████████████████████████████████▍                  | 42/60 [28:44<08:39, 28.87s/it]

Current CPU usage: 50.3%
Current CPU usage: 50.7%
Current CPU usage: 53.7%
Current CPU usage: 50.5%

Processing Resumes:  72%|████████████████████████████████████████████▍                 | 43/60 [29:12<08:04, 28.52s/it]

Current CPU usage: 53.3%
Current CPU usage: 50.8%
Current CPU usage: 51.0%

Processing Resumes:  73%|█████████████████████████████████████████████▍                | 44/60 [29:27<06:32, 24.55s/it]

Current CPU usage: 52.6%
Current CPU usage: 50.9%
Current CPU usage: 50.3%
Current CPU usage: 50.9%
Current CPU usage: 49.9%

Processing Resumes:  75%|██████████████████████████████████████████████▌               | 45/60 [29:57<06:31, 26.10s/it]

Current CPU usage: 52.8%
Current CPU usage: 50.7%
Current CPU usage: 50.8%

Processing Resumes:  77%|███████████████████████████████████████████████▌              | 46/60 [30:18<05:45, 24.67s/it]

Current CPU usage: 53.2%
Current CPU usage: 51.1%
Current CPU usage: 53.1%
Current CPU usage: 50.4%

Processing Resumes:  78%|████████████████████████████████████████████████▌             | 47/60 [30:41<05:11, 23.94s/it]

Current CPU usage: 50.3%
Current CPU usage: 49.9%
Current CPU usage: 50.8%
Current CPU usage: 51.8%
Current CPU usage: 50.5%
Current CPU usage: 49.4%

Processing Resumes:  80%|█████████████████████████████████████████████████▌            | 48/60 [31:14<05:22, 26.85s/it]

Current CPU usage: 50.1%
Current CPU usage: 49.9%
Current CPU usage: 51.9%
Current CPU usage: 50.0%
Current CPU usage: 50.0%

Processing Resumes:  82%|██████████████████████████████████████████████████▋           | 49/60 [31:46<05:11, 28.27s/it]

Current CPU usage: 50.1%
Current CPU usage: 50.2%
Current CPU usage: 52.4%
Current CPU usage: 50.4%
Current CPU usage: 49.9%

Processing Resumes:  83%|███████████████████████████████████████████████████▋          | 50/60 [32:16<04:48, 28.87s/it]

Current CPU usage: 50.5%
Current CPU usage: 50.2%
Current CPU usage: 52.6%
Current CPU usage: 50.5%
Current CPU usage: 50.8%
Current CPU usage: 50.1%
Current CPU usage: 51.5%
Current CPU usage: 53.2%

Processing Resumes:  85%|████████████████████████████████████████████████████▋         | 51/60 [33:07<05:18, 35.40s/it]

Current CPU usage: 51.9%
Current CPU usage: 50.6%
Current CPU usage: 62.4%
Current CPU usage: 50.7%
Current CPU usage: 52.3%

Processing Resumes:  87%|█████████████████████████████████████████████████████▋        | 52/60 [33:34<04:22, 32.87s/it]

Current CPU usage: 50.8%
Current CPU usage: 50.1%
Current CPU usage: 51.1%
Current CPU usage: 50.5%
Current CPU usage: 53.3%

Processing Resumes:  88%|██████████████████████████████████████████████████████▊       | 53/60 [34:04<03:45, 32.24s/it]

Current CPU usage: 51.0%
Current CPU usage: 50.7%
Current CPU usage: 50.3%
Current CPU usage: 50.4%

Processing Resumes:  90%|███████████████████████████████████████████████████████▊      | 54/60 [34:30<03:00, 30.09s/it]

Current CPU usage: 53.6%
Current CPU usage: 50.6%
Current CPU usage: 49.9%
Current CPU usage: 50.1%
Current CPU usage: 50.0%
Current CPU usage: 61.0%

Processing Resumes:  92%|████████████████████████████████████████████████████████▊     | 55/60 [35:01<02:33, 30.62s/it]

Current CPU usage: 50.6%
Current CPU usage: 54.3%
Current CPU usage: 55.4%

Processing Resumes:  93%|█████████████████████████████████████████████████████████▊    | 56/60 [35:23<01:51, 27.94s/it]

Current CPU usage: 49.9%
Current CPU usage: 51.6%
Current CPU usage: 50.3%
Current CPU usage: 50.2%
Current CPU usage: 50.1%
Current CPU usage: 50.3%

Processing Resumes:  95%|██████████████████████████████████████████████████████████▉   | 57/60 [35:57<01:29, 29.69s/it]

Current CPU usage: 52.5%
Current CPU usage: 50.2%
Current CPU usage: 50.3%
Current CPU usage: 50.2%

Processing Resumes:  97%|███████████████████████████████████████████████████████████▉  | 58/60 [36:24<00:57, 28.91s/it]

Current CPU usage: 50.3%
Current CPU usage: 53.2%
Current CPU usage: 50.5%
Current CPU usage: 50.9%
Current CPU usage: 50.3%

Processing Resumes:  98%|████████████████████████████████████████████████████████████▉ | 59/60 [36:51<00:28, 28.28s/it]

Current CPU usage: 50.5%
Current CPU usage: 53.1%
Current CPU usage: 50.5%
Current CPU usage: 50.5%
Current CPU usage: 50.5%
Current CPU usage: 50.3%

Processing Resumes: 100%|██████████████████████████████████████████████████████████████| 60/60 [37:28<00:00, 37.48s/it]

CPU monitor terminated.

✅ Finished in 2250.70 seconds

In [5]:
neww_df = pd.read_csv("DividedDataset/resume_till_1560_rows.csv")
neww_df

,resume,jd,ats_score,new_ats
0,Vishal Kumar \nFull Stack Developer \nMy goal ...,Full job description\nPosition: Junior PHP Dev...,51.84,78
1,Vishal Kumar \nFull Stack Developer \nMy goal ...,Full job description\nJob Summary:\n\nWe are s...,23.41,65
2,Vishal Kumar \nFull Stack Developer \nMy goal ...,Job Title: Sr. Website UI/UX Designer and Deve...,49.52,68
3,Vishal Kumar \nFull Stack Developer \nMy goal ...,We are looking for a passionate and enthusiast...,41.10,85
4,Vishal Kumar \nFull Stack Developer \nMy goal ...,Full job description\nJob Title: Software Engi...,32.23,85
5,Vishal Kumar \nFull Stack Developer \nMy goal ...,Software Tester Intern\n\nAbout Us\n\nWe are ...,29.79,65
6,Vishal Kumar \nFull Stack Developer \nMy goal ...,About Warpfy\n\nWe are a fast-growing cross-bo...,39.58,85
7,Vishal Kumar \nFull Stack Developer \nMy goal ...,Full job description\nWork from office only\n\...,38.12,75
8,Vishal Kumar \nFull Stack Developer \nMy goal ...,Company: Weskill Edutech Private Limited\nLoca...,39.01,65
9,Vishal Kumar \nFull Stack Developer \nMy goal ...,Embark on a transformative journey as a Data A...,18.45,65
10,Vishal Kumar \nFull Stack Developer \nMy goal ...,"\nAs a Full Stack Engineer at Prime Corporate,...",31.12,78
11,Vishal Kumar \nFull Stack Developer \nMy goal ...,Job Summary: The role plays a Plays a crucia...,15.91,65
12,PERSONAL INFORMATION \nFull Name (Full Name as...,Full job description\nPosition: Junior PHP Dev...,45.33,88
13,PERSONAL INFORMATION \nFull Name (Full Name as...,Full job description\nJob Summary:\n\nWe are s...,21.33,85
14,PERSONAL INFORMATION \nFull Name (Full Name as...,Job Title: Sr. Website UI/UX Designer and Deve...,38.96,78
15,PERSONAL INFORMATION \nFull Name (Full Name as...,We are looking for a passionate and enthusiast...,31.30,85
16,PERSONAL INFORMATION \nFull Name (Full Name as...,Full job description\nJob Title: Software Engi...,38.04,85
17,PERSONAL INFORMATION \nFull Name (Full Name as...,Software Tester Intern\n\nAbout Us\n\nWe are ...,30.71,85
18,PERSONAL INFORMATION \nFull Name (Full Name as...,About Warpfy\n\nWe are a fast-growing cross-bo...,29.35,85
19,PERSONAL INFORMATION \nFull Name (Full Name as...,Full job description\nWork from office only\n\...,38.77,78
20,PERSONAL INFORMATION \nFull Name (Full Name as...,Company: Weskill Edutech Private Limited\nLoca...,50.53,88
21,PERSONAL INFORMATION \nFull Name (Full Name as...,Embark on a transformative journey as a Data A...,19.67,78
22,PERSONAL INFORMATION \nFull Name (Full Name as...,"\nAs a Full Stack Engineer at Prime Corporate,...",22.38,85
23,PERSONAL INFORMATION \nFull Name (Full Name as...,Job Summary: The role plays a Plays a crucia...,23.76,78
24,YASH RAJ SUMAN \nYashsuman15@gmail.com | +91-7...,Full job description\nPosition: Junior PHP Dev...,24.20,85
25,YASH RAJ SUMAN \nYashsuman15@gmail.com | +91-7...,Full job description\nJob Summary:\n\nWe are s...,19.03,78
26,YASH RAJ SUMAN \nYashsuman15@gmail.com | +91-7...,Job Title: Sr. Website UI/UX Designer and Deve...,27.40,65
27,YASH RAJ SUMAN \nYashsuman15@gmail.com | +91-7...,We are looking for a passionate and enthusiast...,28.52,88
28,YASH RAJ SUMAN \nYashsuman15@gmail.com | +91-7...,Full job description\nJob Title: Software Engi...,28.30,85
29,YASH RAJ SUMAN \nYashsuman15@gmail.com | +91-7...,Software Tester Intern\n\nAbout Us\n\nWe are ...,25.93,85
30,YASH RAJ SUMAN \nYashsuman15@gmail.com | +91-7...,About Warpfy\n\nWe are a fast-growing cross-bo...,32.03,85
31,YASH RAJ SUMAN \nYashsuman15@gmail.com | +91-7...,Full job description\nWork from office only\n\...,19.29,85
32,YASH RAJ SUMAN \nYashsuman15@gmail.com | +91-7...,Company: Weskill Edutech Private Limited\nLoca...,28.14,88
33,YASH RAJ SUMAN \nYashsuman15@gmail.com | +91-7...,Embark on a transformative journey as a Data A...,14.05,75
34,YASH RAJ SUMAN \nYashsuman15@gmail.com | +91-7...,"\nAs a Full Stack Engineer at Prime Corporate,...",28.10,85
35,YASH RAJ SUMAN \nYashsuman15@gmail.com | +91-7...,Job Summary: The role plays a Plays a crucia...,22.00,78
36,"Yuvraj Walia\nModel Town, Jalandhar, Punjab 14...",Full job description\nPosition: Junior PHP Dev...,47.10,65
37,"Yuvraj Walia\nModel Town, Jalandhar, Punjab 14...",Full job description\nJob Summary:\n\nWe are s...,24.32,45
38,"Yuvraj Walia\nModel Town, Jalandhar, Punjab 14...",Job Title: Sr. Website UI/UX Designer and Deve...,49.94,45
39,"Yuvraj Walia\nModel Town, Jalandhar, Punjab 14...",We are looking for a passionate and enthusiast...,39.81,65
40,"Yuvraj Walia\nModel Town, Jalandhar, Punjab 14...",Full job description\nJob Title: Software Engi...,44.80,65
41,"Yuvraj Walia\nModel Town, Jalandhar, Punjab 14...",Software Tester Intern\n\nAbout Us\n\nWe are ...,36.69,75
42,"Yuvraj Walia\nModel Town, Jalandhar, Punjab 14...",About Warpfy\n\nWe are a fast-growing cross-bo...,34.34,65
43,"Yuvraj Walia\nModel Town, Jalandhar, Punjab 14...",Full job description\nWork from office only\n\...,41.97,45
44,"Yuvraj Walia\nModel Town, Jalandhar, Punjab 14...",Company: Weskill Edutech Private Limited\nLoca...,49.96,45
45,"Yuvraj Walia\nModel Town, Jalandhar, Punjab 14...",Embark on a transformative journey as a Data A...,18.66,45
46,"Yuvraj Walia\nModel Town, Jalandhar, Punjab 14...","\nAs a Full Stack Engineer at Prime Corporate,...",25.34,65
47,"Yuvraj Walia\nModel Town, Jalandhar, Punjab 14...",Job Summary: The role plays a Plays a crucia...,20.43,35
48,Aishleen kaur\nCONTACT\n@ aishkaur024@gmail.c...,Full job description\nPosition: Junior PHP Dev...,40.23,65
49,Aishleen kaur\nCONTACT\n@ aishkaur024@gmail.c...,Full job description\nJob Summary:\n\nWe are s...,16.18,65
50,Aishleen kaur\nCONTACT\n@ aishkaur024@gmail.c...,Job Title: Sr. Website UI/UX Designer and Deve...,44.04,65
51,Aishleen kaur\nCONTACT\n@ aishkaur024@gmail.c...,We are looking for a passionate and enthusiast...,32.90,65
52,Aishleen kaur\nCONTACT\n@ aishkaur024@gmail.c...,Full job description\nJob Title: Software Engi...,28.57,65
53,Aishleen kaur\nCONTACT\n@ aishkaur024@gmail.c...,Software Tester Intern\n\nAbout Us\n\nWe are ...,29.66,65
54,Aishleen kaur\nCONTACT\n@ aishkaur024@gmail.c...,About Warpfy\n\nWe are a fast-growing cross-bo...,30.42,65
55,Aishleen kaur\nCONTACT\n@ aishkaur024@gmail.c...,Full job description\nWork from office only\n\...,30.62,45
56,Aishleen kaur\nCONTACT\n@ aishkaur024@gmail.c...,Company: Weskill Edutech Private Limited\nLoca...,43.20,65
57,Aishleen kaur\nCONTACT\n@ aishkaur024@gmail.c...,Embark on a transformative journey as a Data A...,11.15,35
58,Aishleen kaur\nCONTACT\n@ aishkaur024@gmail.c...,"\nAs a Full Stack Engineer at Prime Corporate,...",23.83,65
59,Aishleen kaur\nCONTACT\n@ aishkaur024@gmail.c...,Job Summary: The role plays a Plays a crucia...,17.10,65

In [8]:
temp_df.head()

,resume,jd,ats_score
0,Vishal Kumar \nFull Stack Developer \nMy goal ...,Full job description\nPosition: Junior PHP Dev...,51.84
1,Vishal Kumar \nFull Stack Developer \nMy goal ...,Full job description\nJob Summary:\n\nWe are s...,23.41
2,Vishal Kumar \nFull Stack Developer \nMy goal ...,Job Title: Sr. Website UI/UX Designer and Deve...,49.52
3,Vishal Kumar \nFull Stack Developer \nMy goal ...,We are looking for a passionate and enthusiast...,41.10
4,Vishal Kumar \nFull Stack Developer \nMy goal ...,Full job description\nJob Title: Software Engi...,32.23