In [2]:
import pandas as pd
from sentence_transformers import SentenceTransformer, util
from tqdm import tqdm

In [3]:
df = pd.read_csv("resume_job_pairs.csv")

In [7]:
df.head()

,resume,jd
0,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nPosition: Junior PHP Dev...
1,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nJob Summary:\n\nWe are s...
2,Abhishek Chaudhary \n ac5712916@gmail.com |...,Job Title: Sr. Website UI/UX Designer and Deve...
3,Abhishek Chaudhary \n ac5712916@gmail.com |...,We are looking for a passionate and enthusiast...
4,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nJob Title: Software Engi...

In [4]:
model = SentenceTransformer('all-MiniLM-L6-v2')

In [5]:
scores = []

In [8]:
for i, row in tqdm(df.iterrows(),total = len(df)):
    jd     = str(row['jd'])
    resume = str(row['resume'])

    embeddings = model.encode([jd, resume], convert_to_tensor= True)

    score = util.cos_sim(embeddings[0], embeddings[1]).item()

    scores.append(round(score* 100, 2))


df['ats_score'] = scores

100%|██████████████████████████████████████████████████████████████████████████████| 1560/1560 [02:22<00:00, 10.96it/s]

In [9]:
df.head()

,resume,jd,ats_score
0,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nPosition: Junior PHP Dev...,26.76
1,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nJob Summary:\n\nWe are s...,21.37
2,Abhishek Chaudhary \n ac5712916@gmail.com |...,Job Title: Sr. Website UI/UX Designer and Deve...,36.91
3,Abhishek Chaudhary \n ac5712916@gmail.com |...,We are looking for a passionate and enthusiast...,30.80
4,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nJob Title: Software Engi...,27.04

In [10]:
df.to_csv("final_dataset.csv", index= False, encoding= 'utf-8')

In [11]:
final_df = pd.read_csv('final_dataset.csv')

In [12]:
final_df.head()

,resume,jd,ats_score
0,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nPosition: Junior PHP Dev...,26.76
1,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nJob Summary:\n\nWe are s...,21.37
2,Abhishek Chaudhary \n ac5712916@gmail.com |...,Job Title: Sr. Website UI/UX Designer and Deve...,36.91
3,Abhishek Chaudhary \n ac5712916@gmail.com |...,We are looking for a passionate and enthusiast...,30.80
4,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nJob Title: Software Engi...,27.04