In [17]:
import pandas as pd 
import numpy as np 
import os 
import fitz

In [18]:
folder = "D:\\DataSet"
files = os.listdir(folder)

In [19]:
resumes = []
files.sort()

In [20]:
i = 1

In [21]:
for file in files:
    
    pdf_path = os.path.join(folder, file)
    text = ""
    doc = fitz.open(pdf_path)
    for page in doc:
        text += page.get_text("text") + "\n"
    doc.close()
    resumes.append(text.strip())

In [40]:
df = pd.DataFrame(resumes)

In [41]:
df = df.rename(columns= {0 : 'resume'})

In [43]:
df.to_csv("resume_dataset.csv", index = False, encoding= "utf-8")
print("CSV created")

CSV created

In [87]:
new_df = pd.read_csv("resume_dataset.csv")

In [88]:
new_df.shape

(136, 1)

In [47]:
final_df = pd.read_csv('final_dataset.csv')

In [48]:
final_df.head()

,resume_text,jobs,ats_score
0,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nPosition: Junior PHP Dev...,26.76
1,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nPosition: Junior PHP Dev...,26.76
2,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nJob Summary:\n\nWe are s...,21.37
3,Abhishek Chaudhary \n ac5712916@gmail.com |...,Job Title: Sr. Website UI/UX Designer and Deve...,36.91
4,Abhishek Chaudhary \n ac5712916@gmail.com |...,We are looking for a passionate and enthusiast...,30.80

In [49]:
jobs_list = final_df['jobs'].unique()

In [52]:
type(jobs_list)

numpy.ndarray

In [53]:
jobs_df = pd.DataFrame(jobs_list)

In [55]:
jobs_df = jobs_df.rename(columns= {0 : "jd"})

In [64]:
jobs_df.head()

                                                  jd
0  Full job description\nPosition: Junior PHP Dev...
1  Full job description\nJob Summary:\n\nWe are s...
2  Job Title: Sr. Website UI/UX Designer and Deve...
3  We are looking for a passionate and enthusiast...
4  Full job description\nJob Title: Software Engi...

In [63]:
jobs_df.shape

(12, 1)

In [66]:
jobs_df.to_csv("jobs_dataset.csv", index= False, encoding= "utf-8")

In [69]:
jobs_dataframe = pd.read_csv('jobs_dataset.csv')
jobs_dataframe.head()

                                                  jd
0  Full job description\nPosition: Junior PHP Dev...
1  Full job description\nJob Summary:\n\nWe are s...
2  Job Title: Sr. Website UI/UX Designer and Deve...
3  We are looking for a passionate and enthusiast...
4  Full job description\nJob Title: Software Engi...

In [70]:
jobs_dataframe.shape

(12, 1)

In [94]:
resumes = pd.read_csv("resume_dataset.csv")   # has column: resume_text
jobs = pd.read_csv('jobs_dataset.csv')         # has column: job_description

In [95]:
resumes = resumes.dropna()

In [96]:


# Add keys to perform cartesian product
resumes["key"] = 1
jobs["key"] = 1

# Cartesian product (cross join)
combined = pd.merge(resumes, jobs, on="key").drop("key", axis=1)

In [97]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   resume  1560 non-null   object
 1   jd      1560 non-null   object
dtypes: object(2)
memory usage: 24.5+ KB

In [98]:
# Save to CSV
combined.to_csv("resume_job_pairs.csv", index=False, encoding="utf-8")

print(f"✅ Combined dataset shape: {combined.shape}")

✅ Combined dataset shape: (1560, 2)

In [99]:
combined_df = pd.read_csv('resume_job_pairs.csv')

In [100]:
combined_df.shape

(1560, 2)

In [101]:
combined_df.head()

,resume,jd
0,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nPosition: Junior PHP Dev...
1,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nJob Summary:\n\nWe are s...
2,Abhishek Chaudhary \n ac5712916@gmail.com |...,Job Title: Sr. Website UI/UX Designer and Deve...
3,Abhishek Chaudhary \n ac5712916@gmail.com |...,We are looking for a passionate and enthusiast...
4,Abhishek Chaudhary \n ac5712916@gmail.com |...,Full job description\nJob Title: Software Engi...

In [102]:
combined_df.isnull().sum()

resume    0
jd        0
dtype: int64

In [103]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   resume  1560 non-null   object
 1   jd      1560 non-null   object
dtypes: object(2)
memory usage: 24.5+ KB